<?php /** @var \Punchout2Go\Punchout\Helper\Transfer $helper */ ?>
<?php $helper = $this->helper(\Punchout2Go\Punchout\Helper\Transfer::class); ?>
<button class="action primary checkout <?= $block->escapeHtml($helper->getButtonCss()) ?>" id="po2go-transfer" <?= !$block->isTransferButtonActive() ? "disabled" : "" ?>>
    <span><?= $block->escapeHtml($helper->getButtonLabel()); ?></span>
</button>
<?php if ($help = $helper->getButtonHelp()): ?>
    <br /><small><?= $block->escapeHtml($help) ?></small>
<?php endif; ?>
<div id="transfer-container"></div>
<?php
$punchoutConfig = json_encode($block->getPunchoutConfig());
$elementsUrl = json_encode($block->getPunchoutElementsUrl());
$debug = json_encode((bool) $block->getIsDebug());
$jsLogging = json_encode((bool) $block->getIsJsLogging());
$closeSessionUrl = json_encode($block->getUrl('punchout/session/closePost'));
?>
<script type="text/x-magento-init">
{
    "#po2go-transfer": {
        "Punchout2Go_Punchout/js/view/transfer-button": {
            "elementId": "#po2go-transfer",
            "debug": <?= $debug ?>,
            "checkoutConfig": {
                "punchoutConfig": <?= $punchoutConfig ?>,
                "elementsUrl": <?= $elementsUrl ?>
            },
            "js_logging": <?= $jsLogging ?>,
            "closeSessionUrl": <?= $closeSessionUrl ?>
        }
    }
}
</script>



