<?php /** @var \Punchout2Go\Punchout\Helper\Transfer $helper */ ?>
<?php $helper = $this->helper(\Punchout2Go\Punchout\Helper\Transfer::class) ?>
<button class="action primary checkout <?= $block->escapeHtml($helper->getButtonCss()) ?>" id="po2go-transfer">
    <span><?= $block->escapeHtml($helper->getButtonLabel()); ?></span>
</button>
<?php if ($help = $helper->getButtonHelp()): ?>
    <br /><small><?= $block->escapeHtml($help) ?></small>
<?php endif; ?>
<div id="transfer-container"></div>
<script type="text/x-magento-init">
    {
        "#po2go-transfer": {
            "Punchout2Go_Punchout/js/view/transfer-button": {
                "elementId": "#po2go-transfer",
                "debug": <?php echo $block->getIsDebug() ?>,
                "checkoutConfig": {
                    "punchoutConfig": <?php echo $block->getPunchoutConfig() ?>,
                    "elementsUrl": <?php echo $block->getPunchoutElementsUrl() ?>
                },
                "closeSessionUrl": "<?php echo $block->getUrl('punchout/session/closePost') ?>"
            }
        }
    }
</script>


