<?php $helper = $this->helper(\Punchout2Go\Punchout\Helper\Session::class); ?>
<script>
    window.reloadParam = "<?php echo $escaper->escapeJs($helper->getFirstLoadParam()) ?>";
</script>
<script type="text/x-magento-init">
    {
        "*" :
            {
                "Punchout2Go_Punchout/js/view/punchout-component" : {
                    "jsReloadSections" : "<?php echo $escaper->escapeJs($helper->getJsReloadSections()); ?>"
                }
            }
    }
</script>

<script type="text/x-magento-init">
    {
        "*" :
            {
                "Punchout2Go_Punchout/js/view/redirect-component" : {
                    "redirectUrl": "<?php echo $escaper->escapeUrl($helper->getPunchoutRedirectUrl()); ?>"
                 }
            }
    }
</script>
