<?php $helper = $this->helper(\Punchout2Go\Punchout\Helper\Session::class); ?>
<script>
    window.reloadParam = <?= $escaper->escapeJs(json_encode($helper->getFirstLoadParam())) ?>;
</script>
<script type="text/x-magento-init">
    {
        "*" :
            {
                "Punchout2Go_Punchout/js/view/punchout-component" : {
                    "jsReloadSections" : "<?= $escaper->escapeUrl($helper->getJsReloadSections()) ?>"
                }
            }
    }
</script>

<script type="text/x-magento-init">
    {
        "*" :
            {
                "Punchout2Go_Punchout/js/view/redirect-component" : {
                    "redirectUrl": "<?= $escaper->escapeUrl($helper->getPunchoutRedirectUrl()) ?>"
                 }
            }
    }
</script>

