<?php $helper = $this->helper(\Punchout2Go\Punchout\Helper\Session::class); ?>
<script>
    window.reloadParam = <?= json_encode($helper->getFirstLoadParam()) ?>;
</script>
<script type="text/x-magento-init">
    {
        "*" :
            {
                "Punchout2Go_Punchout/js/view/punchout-component" : {
                    "jsReloadSections" : <?= json_encode($helper->getJsReloadSections()); ?>
                }
            }
    }
</script>

<script type="text/x-magento-init">
    {
        "*" :
            {
                "Punchout2Go_Punchout/js/view/redirect-component" : {
                    "redirectUrl": <?= json_encode($helper->getPunchoutRedirectUrl()); ?>
                 }
            }
    }
</script>

