name: PHPCS

on:
  pull_request:
    branches:
      - main

jobs:
  run-phpcs:
    name: Run Magento2 PHPCS
    uses: PunchOut2Go/Github-workflows-templates/.github/workflows/ci-tests.yml@51cc248bad17c9c0fc3abbd6a0d92562b2402468  # v1.26.2
    with:
      php_version: "8.1"
      php_coverage_driver: "none"
      use_github_app_token: false

      # Run PHPCS instead of PHPUnit
      enable_phpunit: true
      enable_phpunit_cache: false
      phpunit_command: "composer cs"

      # Disable everything Laravel-related
      enable_laravel: false

      # Disable frontend
      enable_node: false
      enable_frontend_checks: false

      # Disable Trivy
      enable_trivy_fs_vuln: false
      enable_trivy_fs_license: false
      enable_trivy_secret: false

      # Disable artifacts
      upload_artifacts: false
